name: "Terraform Plan and Apply GCP Action"
description: "Run Terraform Plan and Apply in a containerized GitHub Action for GCP, built by Gus Vega. No Terraform install required"
author: "gusvega"
branding:
  icon: "cloud"
  color: "red"

inputs:
  workdir:
    description: "Working directory for Terraform"
    required: false
    default: "."
  secrets:
    description: "JSON string containing secrets"
    required: false
    default: "{}"
  apply:
    description: 'Whether to run terraform apply after plan'
    required: false
    default: 'true'

outputs:
  plan-apply_status:
    description: "Terraform Plan execution status"

runs:
  using: "docker"
  image: "docker://ghcr.io/gusvega-dev/tf-plan-apply-gcp:v1.0.0"